### ISSUE TITLE
"Nodes are not connected!" error.

### ISSUE THREAD

**Issue by Gmogeras** [CarineRey/pcoc#13]
Hi, i'm starting to use PCOC for convergent analysis in a small clade of nematodes, 16 species, so i feed the software with the fasta alignment and my tree that was previously build with *Beast in newick format.
When i get to the step when you use this command "$CMD_PCOC_DOCKER pcoc_det.py -t SpTreeMit16sp.tree -aa Protseq.fa -o output_pcoc_det -m $scenario -f 0.9" i get the next error message:
User / docker
Starting with UID : 1003
2019-02-21 20:01:11,971 - INFO - alignment: Protseq.fa
2019-02-21 20:01:12,055 - INFO - Alphabet usage:
-(4.32%), A(2.79%), C(1.60%), E(1.98%), D(1.95%), G(5.53%), F(14.86%), I(6.73%), H(1.62%), K(2.63%), M(5.21%), L(14.20%), N(3.69%), Q(1.19%), P(2.29%), S(10.32%), R(0.95%), T(3.10%), W(2.04%), V(7.95%), Y(5.04%), X(0.01%) 
2019-02-21 20:01:12,055 - INFO - alignment ok after checking
2019-02-21 20:01:12,055 - INFO - tree: SpTreeMit16sp.tree
2019-02-21 20:01:12,077 - INFO - tree ok after checking
2019-02-21 20:01:12,078 - INFO - Sequence and leaf names match.
Traceback (most recent call last):
  File "/usr/local/bin/pcoc_det.py", line 667, in <module>
    mk_detect(tree_filename, ali_basename, OutDirName)
  File "/usr/local/bin/pcoc_det.py", line 457, in mk_detect
    (allbranchlength, convbranchlength) = g_tree.mk_tree_for_simu(plot=args.plot)
  File "/usr/local/bin/events_placing.py", line 260, in mk_tree_for_simu
    (self.tree_annotated, self.tree_conv_annotated, allbranchlength, convbranchlength) = mk_tree_4_simu(self, topo_met=topo_met, plot=plot)
  File "/usr/local/bin/events_placing.py", line 570, in mk_tree_4_simu
    tconv = build_conv_topo(annotated_tree, conv_combi_events.get_nodes_sim_TorC())
  File "/usr/local/bin/events_placing.py", line 473, in build_conv_topo
    common_anc_conv.prune(l_leaves_to_keep_A, preserve_branch_length=True)
  File "/usr/local/lib/python2.7/dist-packages/ete3/coretype/tree.py", line 527, in prune
    start, node2path = self.get_common_ancestor(to_keep, get_path=True)
  File "/usr/local/lib/python2.7/dist-packages/ete3/coretype/tree.py", line 914, in get_common_ancestor
    ### raise TreeError("Nodes are not connected!")
ete3.coretype.tree.TreeError: 'Nodes are not connected!

[Mit16sp.pdf](https://github.com/CarineRey/pcoc/files/2891012/Mit16sp.pdf)
[Mit16sp2.pdf](https://github.com/CarineRey/pcoc/files/2891013/Mit16sp2.pdf)

what could be the reason, if the previous two steps already show that the nodes are connected?

**Comment by CarineRey** [comment]
Hello,
Take you to report this error.
The scenario in Mit16sp2.pdf doesn't seem convergent. Can you send me the scenario that you used in $scenario and also your convergent species ?

**Comment by Gmogeras** [comment]
$scenario="17,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16/15,1,2,3,4,5,6,7,8,9,10,11,12,13,14/16".

I have this two phylogenies, where in one of them, with nuclear genes,  the clade #5 its sister to #23. In this one, a mitochondrial phylogeny, #5 is sister to #14. This and the species in #16, which also moves from #22 to #23, are the ones where i want to search for adaptive convergence as the reason of the incongruence between phylogenies.

**Comment by Gmogeras** [comment]
Is my $scenario wrong?

**Comment by CarineRey** [comment]
There is may be a misunderstanding about how to build your scenario. Did you use the tutorial (https://github.com/CarineRey/pcoc/wiki#a-prepare-tree-for-detection-analysis-set-putative-convergent-leavesnodes) to write it ?
