### ISSUE TITLE
Get an error when run pcoc_det.py

### ISSUE THREAD

**Issue by taotaoyuan** [CarineRey/pcoc#29]
2023-06-05 21:17:26,111 - INFO - 1 on 16 cpus
2023-06-05 21:17:26,117 - INFO - Profile category uses during estimation:	10	C10
2023-06-05 21:17:26,119 - INFO - Alignment: ../1-Single_Copy/1-mafft/OG0012460.mafft.fa
2023-06-05 21:17:26,120 - INFO - Alignment: 6 seqs 114 sites
2023-06-05 21:17:26,120 - INFO - Alphabet usage:
M(3.36%), A(4.68%), Y(2.19%), V(3.80%), E(1.75%), G(19.01%), K(5.85%), R(7.60%), P(4.97%), I(4.82%), W(2.34%), L(4.09%), T(2.63%), D(4.24%), F(5.56%), S(8.04%), N(2.49%), Q(0.29%), -(8.33%), H(1.32%), C(2.63%)
2023-06-05 21:17:26,121 - INFO - alignment ok after checking
2023-06-05 21:17:26,121 - INFO - tree: FcC_supermatrix_partition.txt.treefile
2023-06-05 21:17:26,123 - INFO - tree ok after checking
2023-06-05 21:17:26,123 - INFO - Sequence and leaf names match.
Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/pcoc/src/pcoc_det.py", line 704, in <module>
    mk_detect(tree_filename, ali_basename, OutDirName)
  File "/home/lx_sky6/yt/soft/pcoc/src/pcoc_det.py", line 488, in mk_detect
    (allbranchlength, convbranchlength) = g_tree.mk_tree_for_simu(plot=args.plot)
  File "/home/lx_sky6/yt/soft/pcoc/src/events_placing.py", line 261, in mk_tree_for_simu
    (self.tree_annotated, self.tree_conv_annotated, allbranchlength, convbranchlength) = mk_tree_4_simu(self, topo_met=topo_met, plot=plot)
  File "/home/lx_sky6/yt/soft/pcoc/src/events_placing.py", line 511, in mk_tree_4_simu
    if bl_new >= 0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by qw-wq** [comment]
I ran with test data and got a similar error！

**docker run -e LOCAL_USER_ID=`id -u $USER` --rm -v $PWD:$PWD -e CWD=$PWD carinerey/pcoc pcoc_det.py -t  tree_dir/tree.nw -aa ali.fa -o  output_pcoc_det -m $scenario  -f 0.8 --plot --reorder -ph $candidates**

Working directory : /software/pcoc-master/data/test
User / docker
Starting with UID : 1000
2024-03-19 08:56:34,800 - INFO - 1 on 128 cpus
2024-03-19 08:56:34,802 - INFO - Profile category uses during estimation:       10      C10
2024-03-19 08:56:34,802 - INFO - Alignment: ali.fa
2024-03-19 08:56:34,866 - INFO - Alignment: 79 seqs 970 sites
2024-03-19 08:56:34,867 - INFO - Alphabet usage:
-(56.00%), A(3.36%), C(0.25%), E(3.71%), D(1.99%), G(3.02%), F(2.21%), I(2.34%), H(1.27%), K(2.40%), M(1.07%), L(4.68%), N(0.91%), Q(1.64%), P(2.47%), S(2.25%), R(2.83%), T(2.21%), W(0.94%), V(2.89%), Y(1.25%), X(0.31%)
2024-03-19 08:56:34,867 - INFO - alignment ok after checking
2024-03-19 08:56:34,867 - INFO - tree: tree_dir/tree.nw
2024-03-19 08:56:34,871 - INFO - tree ok after checking
2024-03-19 08:56:34,871 - INFO - Sequence and leaf names match.
Traceback (most recent call last):
  File "/usr/local/bin/pcoc_det.py", line 703, in <module>
    mk_detect(tree_filename, ali_basename, OutDirName)
  File "/usr/local/bin/pcoc_det.py", line 620, in mk_detect
    new_seq = SeqRecord.SeqRecord(Seq.Seq("".join(filter_l(list(seq.seq),dict_pos_filtered[model]))), seq.id, "", "")
  File "/usr/local/bin/pcoc_det.py", line 445, in filter_l
    new_l[i] = l[p-1]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
