### ISSUE TITLE
pcoc_det.py broken help (argparse problem)

### ISSUE THREAD

**Issue by drwhitehouse** [CarineRey/pcoc#7]
Hi, the help for "pcoc_det.py" appears to be broken:

```
Singularity pcoc.simg:~> pcoc_det.py --help
Traceback (most recent call last):
  File "/usr/local/bin/pcoc_det.py", line 142, in <module>
    args = parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/usr/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/usr/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/usr/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/usr/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/usr/lib/python2.7/argparse.py", line 517, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib/python2.7/argparse.py", line 603, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character ')' (0x29) at index 90

```
With a "short" option it looks a bit better but argparse is still thoroughly confused:

```
Singularity pcoc.simg:~> pcoc_det.py -help
usage: pcoc_det.py [-h] [--version] -t TREE -aa ALI -m "x/y,z/..." -o
                   OUTPUT_DIR [-f FILTER_T] [-f_pcoc FILTER_T_PCOC]
                   [-f_pc FILTER_T_PC] [-f_oc FILTER_T_OC] [-ph PH] [--plot]
                   [--plot_complete_ali] [-plot_title PLOT_TITLE] [--reorder]
                   [--svg] [--no_cleanup_fasta] [-CATX_est {10,60}] [--gamma]
                   [--inv_gamma] [--max_gap_allowed MAX_GAP_ALLOWED]
                   [--max_gap_allowed_in_conv_leaves MAX_GAP_ALLOWED_IN_CONV_LEAVES]
                   [--no_cleanup] [-LD_LIB LD_LIBRARY_PATH] [--debug]
pcoc_det.py: error: argument -h/--help: ignored explicit argument 'elp'
```
I suspect that this occurs because you are using the "%" character in your help output but something is causing this to be interpreted as a format string.

**Comment by CarineRey** [comment]
Thank you for the feedback. I fixed it.
